theme = "gruvbox_dark_hard"

[editor]
line-number = "absolute"
mouse = true
auto-completion = true
auto-info = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"

[keys.normal."backspace"]
e = [":sh cargo run"]
r = [":w", ":config-reload"]
o = [":config-open"]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-signature-help-docs = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
