icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
[[block.click]]
button = "left"
cmd = "kitty htop"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:M)/$mem_used_percents.eng(w:1)"
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "kitty pulsemixer"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%r / %Y-%m-%d') "
#format = " $timestamp.datetime(f:'%I:%M:%S / %Y-%m-%d') "
